[package]
name = "ferrumdb-wal"
description = "Redo log and crash recovery for FerrumDB"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
ferrumdb-page = { path = "../ferrumdb-page" }
thiserror.workspace = true
crc32fast.workspace = true

[dev-dependencies]
tempfile = { workspace = true }
ferrumdb-space = { path = "../ferrumdb-space" }
